services:
  # -- FRONTEND --
  admin:
    build:
      context: ./frontend/admin
      dockerfile: Dockerfile
    image: admin-frontend:latest
    ports:
      - "5174:80"
    networks:
      - bamboom-network
    depends_on:
      - api-gateway

  player:
    build:
      context: ./frontend/player
      dockerfile: Dockerfile
    image: player-frontend:latest
    ports:
      - "5173:80"
    networks:
      - bamboom-network
    depends_on:
      - api-gateway

  # -- API GATEWAY --
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    image: api-gateway:latest
    ports:
      - "8000:8000"
    networks:
      - bamboom-network
    environment:
      - PLAYER_IDENTITY_URL=http://player-identity:3000
      - LOBBY_MATCH_URL=http://lobby-match:3000
      - DECK_WORKSHOP_URL=http://deck-workshop:3000
      - CARD_FORGE_URL=http://card-forge:3000
      - PROGRESS_URL=http://progress:3000
    depends_on:
      - player-identity
      - lobby-match
      - deck-workshop
      - card-forge
      - progress

  # -- MICROSERVIZI --
  player-identity:
    build:
      context: ./micro-services/player-identity
      dockerfile: Dockerfile
    image: player-identity:latest
    ports:
      - "3001:3000"
    networks:
      - bamboom-network

  lobby-match:
    build:
      context: ./micro-services/lobby-match
      dockerfile: Dockerfile
    image: lobby-match:latest
    ports:
      - "3002:3000"
    networks:
      - bamboom-network

  deck-workshop:
    build:
      context: ./micro-services/deck-workshop
      dockerfile: Dockerfile
    image: deck-workshop:latest
    ports:
      - "3003:3000"
    networks:
      - bamboom-network

  card-forge:
    build:
      context: ./micro-services/card-forge
      dockerfile: Dockerfile
    image: card-forge:latest
    ports:
      - "3004:3000"
    networks:
      - bamboom-network

  progress:
    build:
      context: .
      dockerfile: micro-services/progress/Dockerfile
    image: progress:latest
    ports:
      - "3005:3000"
    networks:
      - bamboom-network

networks:
  bamboom-network:
    driver: bridge
