# micro-services/progress/.scalafix.conf
# Regole Scalafix per game-observatory (solo sintattiche, no SemanticDB).
# si aggiungono qui le regole di refactoring automatico

rules = [
  DisableSyntax
]

DisableSyntax.noVars = true
DisableSyntax.noNulls = true
DisableSyntax.noThrows = true
DisableSyntax.noReturns = true
DisableSyntax.noWhile = true