name: lobby-match

on:
  workflow_call:
  push:
    tags:
      - 'lobby-match-v*'

permissions:
  contents: read

jobs:
  verify:
    if: ${{ github.ref_type != 'tag' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/verify-node
        with:
          project: lobby-match
          path: micro-services/lobby-match
          image: lobby-match
          codecov-token: ${{ secrets.CODECOV_TOKEN }}

  codeql:
    if: ${{ github.ref_type != 'tag' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/codeql-js-ts
        with:
          name: lobby-match
          path: micro-services/lobby-match

  release:
    if: ${{ github.ref_type == 'tag' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/release-image
        with:
          project: lobby-match
          image: lobby-match
