name: player-identity

on:
  workflow_call:
  push:
    tags:
      - 'player-identity-v*'

permissions:
  contents: read

jobs:
  verify:
    if: ${{ github.ref_type != 'tag' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/verify-node
        with:
          project: player-identity
          path: micro-services/player-identity
          image: player-identity
          codecov-token: ${{ secrets.CODECOV_TOKEN }}

  codeql:
    if: ${{ github.ref_type != 'tag' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/codeql-js-ts
        with:
          name: player-identity
          path: micro-services/player-identity

  release:
    if: ${{ github.ref_type == 'tag' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/release-image
        with:
          project: player-identity
          image: player-identity
