name: card-forge

on:
  workflow_call:
  push:
    tags:
      - 'card-forge-v*'

permissions:
  contents: read

jobs:
  verify:
    if: ${{ github.ref_type != 'tag' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/verify-node
        with:
          project: card-forge
          path: micro-services/card-forge
          image: card-forge
          codecov-token: ${{ secrets.CODECOV_TOKEN }}

  release:
    if: ${{ github.ref_type == 'tag' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/release-image
        with:
          project: card-forge
          image: card-forge
