name: deck-workshop

on:
  workflow_call:
  push:
    tags:
      - 'deck-workshop-v*'

permissions:
  contents: read

jobs:
  verify:
    if: ${{ github.ref_type != 'tag' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/verify-node
        with:
          project: deck-workshop
          path: micro-services/deck-workshop
          image: deck-workshop
          codecov-token: ${{ secrets.CODECOV_TOKEN }}

  codeql:
    if: ${{ github.ref_type != 'tag' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/codeql-js-ts
        with:
          name: deck-workshop
          path: micro-services/deck-workshop

  release:
    if: ${{ github.ref_type == 'tag' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/release-image
        with:
          project: deck-workshop
          image: deck-workshop
