name: api-gateway

on:
  workflow_call:
  push:
    tags:
      - 'api-gateway-v*'

permissions:
  contents: read

jobs:
  verify:
    if: ${{ github.ref_type != 'tag' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/verify-node
        with:
          project: api-gateway
          path: api-gateway
          image: api-gateway
          codecov-token: ${{ secrets.CODECOV_TOKEN }}

  codeql:
    if: ${{ github.ref_type != 'tag' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/codeql-js-ts
        with:
          name: api-gateway
          path: api-gateway

  release:
    if: ${{ github.ref_type == 'tag' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/release-image
        with:
          project: card-forge
          image: card-forge
